version: '1'

services:

  compose-test:

    image: otivisan22/dockerjenkins

    links:

      - compose-db

    command: /usr/bin/curl compose-db:6379

  compose-db:

    image: redis

    expose:

      - "6379"

